[http]
  [http.routers]
    [http.routers.vcc-app]
      rule = "Host(`vcc.myinvoices.today`)"
      service = "vcc-app"
      entryPoints = ["web"]

  [http.services]
    [http.services.vcc-app]
      [http.services.vcc-app.loadBalancer]
        [[http.services.vcc-app.loadBalancer.servers]]
          url = "http://127.0.0.1:3000"
